#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

PROJECT="$TMP_ROOT/project with spaces"
mkdir -p "$PROJECT/scripts" "$PROJECT/.claude/commands" "$PROJECT/.opencode/commands"
cp "$ROOT/scripts/export-opencode.sh" "$PROJECT/scripts/"

cat > "$PROJECT/.claude/commands/sdk-alpha.md" <<'EOF'
---
description: Alpha description remains byte-for-byte
argument-hint: "[feature name]"
---

# Alpha

Run the alpha workflow.
EOF

cat > "$PROJECT/.claude/commands/sdk-beta.md" <<'EOF'
---
description: Beta accepts explicit arguments
argument-hint: "[target]"
---

# Beta

Use these arguments: $ARGUMENTS
EOF

MISSING="$TMP_ROOT/missing export project"
mkdir -p "$MISSING/scripts" "$MISSING/.claude/commands"
cp "$PROJECT/scripts/export-opencode.sh" "$MISSING/scripts/"
cp "$PROJECT/.claude/commands/sdk-alpha.md" "$MISSING/.claude/commands/"
if bash "$MISSING/scripts/export-opencode.sh" --check >/dev/null 2>&1; then
  echo "A missing export unexpectedly passed --check" >&2
  exit 1
fi
[ ! -e "$MISSING/.opencode" ] || {
  echo "Check mode mutated a project with no destination" >&2
  exit 1
}

printf 'manual command\n' > "$PROJECT/.opencode/commands/manual.md"
printf 'manual sdk command\n' > "$PROJECT/.opencode/commands/sdk-manual.md"
cat > "$PROJECT/.opencode/commands/sdk-stale.md" <<'EOF'
---
description: stale
---

<!-- GENERATED BY spec-driven-kit export-opencode; source: .claude/commands/sdk-stale.md; DO NOT EDIT -->

$ARGUMENTS
EOF

bash "$PROJECT/scripts/export-opencode.sh"

alpha="$PROJECT/.opencode/commands/sdk-alpha.md"
beta="$PROJECT/.opencode/commands/sdk-beta.md"
[ -f "$alpha" ] && [ -f "$beta" ]
[ ! -e "$PROJECT/.opencode/commands/sdk-stale.md" ]
[ "$(cat "$PROJECT/.opencode/commands/manual.md")" = "manual command" ]
[ "$(cat "$PROJECT/.opencode/commands/sdk-manual.md")" = "manual sdk command" ]
grep -Fxq 'description: Alpha description remains byte-for-byte' "$alpha"
! grep -q '^argument-hint:' "$alpha"
! grep -Eq '^(agent|model):' "$alpha"
grep -Fq '<!-- GENERATED BY spec-driven-kit export-opencode;' "$alpha"
[ "$(grep -oF '$ARGUMENTS' "$alpha" | wc -l | tr -d ' ')" -eq 1 ]
[ "$(grep -oF '$ARGUMENTS' "$beta" | wc -l | tr -d ' ')" -eq 1 ]

bash "$PROJECT/scripts/export-opencode.sh" --check
cp -a "$PROJECT/.opencode/commands" "$TMP_ROOT/idempotent snapshot"
bash "$PROJECT/scripts/export-opencode.sh"
diff -qr "$TMP_ROOT/idempotent snapshot" "$PROJECT/.opencode/commands"

printf '\nlocal drift\n' >> "$alpha"
if bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null 2>&1; then
  echo "A modified generated command unexpectedly passed --check" >&2
  exit 1
fi
grep -q 'local drift' "$alpha"
bash "$PROJECT/scripts/export-opencode.sh" >/dev/null
! grep -q 'local drift' "$alpha"
bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null

# Source changes invalidate check mode and are applied on the next write.
sed -i 's/Alpha description remains byte-for-byte/Alpha description changed at source/' \
  "$PROJECT/.claude/commands/sdk-alpha.md"
if bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null 2>&1; then
  echo "A changed source unexpectedly passed --check" >&2
  exit 1
fi
bash "$PROJECT/scripts/export-opencode.sh" >/dev/null
grep -Fxq 'description: Alpha description changed at source' "$alpha"
bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null

# A stale generated file is drift in check mode and is removed only in write mode.
cat > "$PROJECT/.opencode/commands/sdk-old.md" <<'EOF'
---
description: old
---

<!-- GENERATED BY spec-driven-kit export-opencode; source: .claude/commands/sdk-old.md; DO NOT EDIT -->

$ARGUMENTS
EOF
if bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null 2>&1; then
  echo "A stale generated command unexpectedly passed --check" >&2
  exit 1
fi
bash "$PROJECT/scripts/export-opencode.sh" >/dev/null
[ ! -e "$PROJECT/.opencode/commands/sdk-old.md" ]

# Preflight must reject unsupported frontmatter without changing any destination file.
cp -a "$PROJECT/.opencode/commands" "$TMP_ROOT/preflight snapshot"
cat > "$PROJECT/.claude/commands/sdk-invalid.md" <<'EOF'
---
description: invalid fixed model
model: provider/fixed-model
---

Never render this.
EOF
if bash "$PROJECT/scripts/export-opencode.sh" >/dev/null 2>&1; then
  echo "Unsupported frontmatter unexpectedly exported" >&2
  exit 1
fi
diff -qr "$TMP_ROOT/preflight snapshot" "$PROJECT/.opencode/commands"
rm "$PROJECT/.claude/commands/sdk-invalid.md"

# Duplicate argument interpolation is rejected before destination reconciliation.
cat > "$PROJECT/.claude/commands/sdk-invalid.md" <<'EOF'
---
description: duplicate arguments
argument-hint: "[args]"
---

$ARGUMENTS and $ARGUMENTS
EOF
if bash "$PROJECT/scripts/export-opencode.sh" >/dev/null 2>&1; then
  echo "Duplicate argument interpolation unexpectedly exported" >&2
  exit 1
fi
diff -qr "$TMP_ROOT/preflight snapshot" "$PROJECT/.opencode/commands"
rm "$PROJECT/.claude/commands/sdk-invalid.md"

# A manual sdk-* collision is preserved and blocks the whole export.
cat > "$PROJECT/.claude/commands/sdk-manual.md" <<'EOF'
---
description: source colliding with a manual OpenCode command
argument-hint: "[args]"
---

Do not overwrite the manual file.
EOF
if bash "$PROJECT/scripts/export-opencode.sh" >/dev/null 2>&1; then
  echo "Manual sdk command collision unexpectedly exported" >&2
  exit 1
fi
[ "$(cat "$PROJECT/.opencode/commands/sdk-manual.md")" = "manual sdk command" ]
diff -qr "$TMP_ROOT/preflight snapshot" "$PROJECT/.opencode/commands"
rm "$PROJECT/.claude/commands/sdk-manual.md"

bash "$PROJECT/scripts/export-opencode.sh" --check >/dev/null
if bash "$PROJECT/scripts/export-opencode.sh" --unknown >/dev/null 2>&1; then
  echo "Unknown option unexpectedly succeeded" >&2
  exit 1
fi

if grep -Eq '\b(curl|wget)\b' "$PROJECT/scripts/export-opencode.sh"; then
  echo "Exporter must not access the network" >&2
  exit 1
fi

echo "export-opencode Bash matrix passed."
