#!/usr/bin/env bash
# Generate native OpenCode commands from the canonical Claude command sources.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
MODE="write"
STAGE=""
DEST=""
BACKUP=""
SWAP_PENDING=0

usage() {
  cat <<'EOF'
Usage: scripts/export-opencode.sh [--check] [--root PATH]

  --check      Validate that .opencode/commands is current without changing it.
  --root PATH  Use PATH as the project root (defaults to the parent of this script).
EOF
}

export_error() {
  printf 'export-opencode: %s\n' "$*" >&2
}

cleanup() {
  if [ "$SWAP_PENDING" -eq 1 ] && [ -n "$BACKUP" ] && [ -d "$BACKUP" ] && [ ! -e "$DEST" ]; then
    mv -- "$BACKUP" "$DEST" 2>/dev/null || true
  fi
  if [ -n "$STAGE" ] && [ -d "$STAGE" ]; then
    rm -rf -- "$STAGE"
  fi
}
trap cleanup EXIT
trap 'exit 130' HUP INT TERM

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      [ "$MODE" = "write" ] || { export_error "--check was provided more than once"; exit 2; }
      MODE="check"
      shift
      ;;
    --root)
      [ "$#" -ge 2 ] || { export_error "--root requires a path"; exit 2; }
      [ -d "$2" ] || { export_error "project root does not exist: $2"; exit 2; }
      ROOT="$(cd -- "$2" && pwd -P)"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      export_error "unknown argument: $1"
      usage >&2
      exit 2
      ;;
  esac
done

SOURCE_DIR="$ROOT/.claude/commands"
DEST_PARENT="$ROOT/.opencode"
DEST="$DEST_PARENT/commands"

[ -d "$SOURCE_DIR" ] || { export_error "source directory not found: $SOURCE_DIR"; exit 2; }
[ ! -L "$SOURCE_DIR" ] || { export_error "source directory may not be a symlink: $SOURCE_DIR"; exit 2; }

if [ -e "$DEST_PARENT" ]; then
  [ -d "$DEST_PARENT" ] || { export_error "destination parent is not a directory: $DEST_PARENT"; exit 2; }
  [ ! -L "$DEST_PARENT" ] || { export_error "destination parent may not be a symlink: $DEST_PARENT"; exit 2; }
fi
if [ -e "$DEST" ]; then
  [ -d "$DEST" ] || { export_error "destination is not a directory: $DEST"; exit 2; }
  [ ! -L "$DEST" ] || { export_error "destination may not be a symlink: $DEST"; exit 2; }
fi

shopt -s nullglob
sources=("$SOURCE_DIR"/sdk-*.md)
[ "${#sources[@]}" -gt 0 ] || { export_error "no sdk-*.md command sources found"; exit 2; }

if [ "$MODE" = "check" ]; then
  STAGE="$(mktemp -d "${TMPDIR:-/tmp}/sdk-opencode-check.XXXXXX")" || {
    export_error "could not create temporary check directory"
    exit 2
  }
else
  STAGE="$(mktemp -d "$ROOT/.sdk-opencode-export.XXXXXX")" || {
    export_error "could not create staging directory under project root"
    exit 2
  }
fi
RENDERED="$STAGE/rendered"
MERGED="$STAGE/merged"
mkdir -p -- "$RENDERED" "$MERGED"

is_generated_file() {
  local path="$1"
  grep -Eq '^<!-- GENERATED BY spec-driven-kit export-opencode; source: \.claude/commands/sdk-[a-z0-9][a-z0-9-]*\.md; DO NOT EDIT -->\r?$' "$path"
}

literal_argument_count() {
  awk '
    {
      line = $0
      while ((position = index(line, "$ARGUMENTS")) > 0) {
        count++
        line = substr(line, position + 10)
      }
    }
    END { print count + 0 }
  ' "$1"
}

render_source() {
  local source="$1" output="$2" name="$3"
  local source_rel=".claude/commands/$name"

  if ! awk -v source_rel="$source_rel" '
    function abort(message) {
      print "export-opencode: " source_rel ": " message > "/dev/stderr"
      failed = 1
      exit 42
    }
    {
      sub(/\r$/, "")
    }
    NR == 1 {
      if ($0 != "---") abort("frontmatter must start on the first line")
      in_frontmatter = 1
      next
    }
    in_frontmatter {
      if ($0 == "---") {
        if (description_count != 1) abort("frontmatter requires exactly one non-empty description")
        in_frontmatter = 0
        body_started = 1
        print "---"
        print description
        print "---"
        print ""
        print "<!-- GENERATED BY spec-driven-kit export-opencode; source: " source_rel "; DO NOT EDIT -->"
        print ""
        next
      }
      if ($0 ~ /^description:[ \t]*[^ \t].*$/) {
        description_count++
        if (description_count > 1) abort("description is duplicated")
        if (index($0, "$ARGUMENTS") > 0) abort("description may not contain $ARGUMENTS")
        description = $0
        next
      }
      if ($0 ~ /^argument-hint:[ \t]*.*$/) {
        argument_hint_count++
        if (argument_hint_count > 1) abort("argument-hint is duplicated")
        next
      }
      if ($0 ~ /^[ \t]*$/) next
      abort("unsupported frontmatter key; only description and argument-hint are accepted")
    }
    {
      body_lines++
      line = $0
      while ((position = index(line, "$ARGUMENTS")) > 0) {
        argument_count++
        line = substr(line, position + 10)
      }
      print $0
    }
    END {
      if (failed) exit 42
      if (in_frontmatter || !body_started) {
        print "export-opencode: " source_rel ": frontmatter closing delimiter is missing" > "/dev/stderr"
        exit 42
      }
      if (argument_count > 1) {
        print "export-opencode: " source_rel ": source contains $ARGUMENTS more than once" > "/dev/stderr"
        exit 42
      }
      if (argument_count == 0) {
        print ""
        print "Argumentos fornecidos pelo usuario:"
        print ""
        print "$ARGUMENTS"
      }
    }
  ' "$source" > "$output"; then
    rm -f -- "$output"
    return 1
  fi

  local expected_description actual_description argument_count marker_count
  expected_description="$(sed -n 's/\r$//; /^description:/ { p; q; }' "$source")"
  actual_description="$(sed -n '2{s/\r$//;p;q;}' "$output")"
  [ "$actual_description" = "$expected_description" ] || {
    export_error "$source_rel: generated description does not match the source"
    return 1
  }
  if sed -n '2,/^---\r*$/p' "$output" | grep -Eq '^(argument-hint|agent|model):'; then
    export_error "$source_rel: generated frontmatter contains a forbidden key"
    return 1
  fi
  argument_count="$(literal_argument_count "$output")"
  [ "$argument_count" -eq 1 ] || {
    export_error "$source_rel: generated command must contain \$ARGUMENTS exactly once (found $argument_count)"
    return 1
  }
  marker_count="$(grep -Ec '^<!-- GENERATED BY spec-driven-kit export-opencode;' "$output" || true)"
  [ "$marker_count" -eq 1 ] || {
    export_error "$source_rel: generated marker is missing or duplicated"
    return 1
  }
}

for source in "${sources[@]}"; do
  [ -f "$source" ] && [ ! -L "$source" ] || {
    export_error "command source must be a regular non-symlink file: $source"
    exit 2
  }
  name="$(basename -- "$source")"
  if ! printf '%s\n' "$name" | grep -Eq '^sdk-[a-z0-9][a-z0-9-]*\.md$'; then
    export_error "unsafe command filename: $name"
    exit 2
  fi
  render_source "$source" "$RENDERED/$name" "$name" || exit 2
done

if [ -d "$DEST" ]; then
  for existing in "$DEST"/sdk-*.md; do
    [ ! -L "$existing" ] || { export_error "sdk command destination may not be a symlink: $existing"; exit 2; }
  done
  cp -a -- "$DEST/." "$MERGED/"
fi

# Reconcile only files carrying this exporter's generated marker. Manual commands,
# including manual sdk-*.md files, are preserved and therefore block collisions.
for existing in "$MERGED"/sdk-*.md; do
  if is_generated_file "$existing"; then
    rm -f -- "$existing"
  fi
done

for generated in "$RENDERED"/sdk-*.md; do
  name="$(basename -- "$generated")"
  if [ -e "$MERGED/$name" ] || [ -L "$MERGED/$name" ]; then
    export_error "refusing to overwrite manual OpenCode command: $DEST/$name"
    exit 2
  fi
  cp -- "$generated" "$MERGED/$name"
done

if [ "$MODE" = "check" ]; then
  if [ ! -d "$DEST" ]; then
    export_error "OpenCode export is missing: $DEST"
    exit 1
  fi
  if ! diff -qr -- "$DEST" "$MERGED" >/dev/null; then
    export_error "OpenCode export is stale; run scripts/export-opencode.sh"
    exit 1
  fi
  printf 'export-opencode: up to date (%s command(s)).\n' "${#sources[@]}"
  exit 0
fi

if [ -d "$DEST" ] && diff -qr -- "$DEST" "$MERGED" >/dev/null; then
  printf 'export-opencode: already up to date (%s command(s)).\n' "${#sources[@]}"
  exit 0
fi

mkdir -p -- "$DEST_PARENT"
if [ -d "$DEST" ]; then
  BACKUP="$STAGE/original-commands"
  SWAP_PENDING=1
  mv -- "$DEST" "$BACKUP"
  if ! mv -- "$MERGED" "$DEST"; then
    export_error "destination swap failed; restoring the previous export"
    if [ ! -e "$DEST" ]; then
      mv -- "$BACKUP" "$DEST" || true
    fi
    SWAP_PENDING=0
    exit 2
  fi
  SWAP_PENDING=0
else
  if ! mv -- "$MERGED" "$DEST"; then
    export_error "could not install generated commands"
    exit 2
  fi
fi

printf 'export-opencode: generated %s command(s) in %s.\n' "${#sources[@]}" "$DEST"
